feat(screen) : change screen of preset for main pc startup

diff --git a/screen b/screen
--- a/screen
+++ b/screen
@@ -195,8 +195,8 @@ function presetStartup() {
     local screens=$(getConnectedScreen all "$ignoreScreen")
     [ -z "$screens" ] && error "Preset : No screen found" && exit 1
 
-    echo -e "$screens" | grep -Evq "DP-3|HDMI-1" && \
-        error "Preset : Required screen \"DP-3, HDMI-1\" not found" && exit 1
+    echo -e "$screens" | grep -Evq "DP-0|DP-2" && \
+        error "Preset : Required screen \"DP-0, DP-2\" not found" && exit 1
 
     if [ -z "$choosePreset" ]; then
         choosePreset=$(echo -e "enable\ndisable" | rofi -dmenu -p "Choose preset")
@@ -204,11 +204,11 @@ function presetStartup() {
 
     case $choosePreset in
         enable)
-            xrandr --output DP-3 --mode 1920x1080 --primary
-            xrandr --output HDMI-1 --mode 1366x768 --right-of DP-3;;
+            xrandr --output DP-2 --mode 1920x1080 --primary
+            xrandr --output DP-0 --mode 1920x1080 --right-of DP-2;;
         disable)
-            xrandr --output DP-3 --auto
-            xrandr --output HDMI-1 --off;;
+            xrandr --output DP-2 --auto
+            xrandr --output DP-0 --off;;
         *)
             error "Preset : Unknown action" &&
             exit 1;;
